# Generated by Django 5.0.8 on 2026-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Contract end date for contract employees', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('confirmed', 'Confirmed Staff'), ('contract', 'Contract Staff')], db_index=True, default='confirmed', help_text='Type of employment: confirmed or contract staff', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal email address', max_length=254),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='residential_location',
            field=models.CharField(blank=True, help_text='Residential location/address', max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Work email address', max_length=254),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employment_type'], name='employee_pr_employm_57c954_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['contract_end_date'], name='employee_pr_contrac_356320_idx'),
        ),
    ]
