# Generated by Django 5.0.8 on 2026-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeeprofile_bank_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_start_date',
            field=models.DateField(blank=True, help_text='Date the employee joined the employer', null=True),
        ),
    ]
