# Generated by Django 5.0.8 on 2026-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeeprofile_employment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='position',
            field=models.CharField(blank=True, default='', help_text="HR user's job title/position (e.g. 'HR Manager')", max_length=100),
        ),
    ]
