# Generated by Django 5.0.8 on 2026-02-18 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company/Organization name', max_length=255, unique=True)),
                ('registration_number', models.CharField(help_text='Company registration number', max_length=100, unique=True)),
                ('address', models.TextField(help_text='Physical address')),
                ('payroll_cycle_day', models.IntegerField(default=25, help_text='Day of month when payroll is processed (default: 25th)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('hr_contact_name', models.CharField(max_length=255)),
                ('hr_contact_email', models.EmailField(max_length=254)),
                ('hr_contact_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the employer is currently active in the system')),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarded_by', models.ForeignKey(help_text='254 Capital admin who onboarded this employer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'employers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='employers_name_a261b2_idx'), models.Index(fields=['is_active'], name='employers_is_acti_7130f1_idx')],
            },
        ),
    ]
