# Generated by Django 5.0 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='interest_method',
            field=models.CharField(
                choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')],
                default='flat',
                help_text='Interest calculation method: flat (default) or reducing_balance (EMI)',
                max_length=20,
            ),
        ),
    ]
