# Generated by Django 5.0 on 2026-06-11

from decimal import Decimal
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_interest_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='interest_rate',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0.05'),
                help_text='Monthly interest rate as decimal (e.g., 0.05 for 5%). Range: 0.01% to 100%',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.0001')),
                    django.core.validators.MaxValueValidator(Decimal('1.0')),
                ],
            ),
        ),
    ]
