# Generated by Django 5.0.8 on 2026-09-08 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employer_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='interest_method',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')], default='reducing_balance', help_text='Interest calculation method: reducing_balance (EMI, default) or flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Monthly interest rate as decimal (e.g., 0.05 for 5%). Range: 0.01% to 100%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
