# Generated by Django 5.0.8 on 2026-02-18 06:25

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('national_id_front', 'National ID (Front)'), ('national_id_back', 'National ID (Back)'), ('payslip_1', 'Payslip 1 (Most Recent)'), ('payslip_2', 'Payslip 2'), ('payslip_3', 'Payslip 3'), ('check_off_agreement', 'Check-Off Agreement'), ('disbursement_receipt', 'Disbursement Receipt'), ('remittance_proof', 'Remittance Proof'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(help_text='Allowed formats: PDF, JPG, PNG. Max size: 5MB', upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='Loan application this document is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication')),
                ('employer', models.ForeignKey(blank=True, help_text='Employer this document is attached to (e.g., agreements)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employers.employer')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application'], name='documents_applica_2654b3_idx'), models.Index(fields=['employer'], name='documents_employe_76913b_idx'), models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'), models.Index(fields=['uploaded_by'], name='documents_uploade_aad805_idx')],
            },
        ),
    ]
