# Generated by Django 5.0.8 on 2026-05-11 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name (must be unique)', max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the organization')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for the organization', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the organization is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='HR admin who created this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('organization_created', 'Organization Created'), ('organization_updated', 'Organization Updated'), ('organization_deactivated', 'Organization Deactivated'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('loan_application_viewed', 'Loan Application Viewed'), ('loan_application_approved', 'Loan Application Approved'), ('loan_application_declined', 'Loan Application Declined'), ('authorization_failed', 'Authorization Failed')], db_index=True, help_text='Type of event that occurred', max_length=50)),
                ('target_resource_type', models.CharField(blank=True, help_text='Type of resource affected (e.g., loan_application, role)', max_length=50)),
                ('target_resource_id', models.UUIDField(blank=True, help_text='ID of the affected resource', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the request')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, default='success', help_text='Whether the action succeeded or failed', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the event')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_user', models.ForeignKey(blank=True, help_text='User who was the target of the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (actor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization context of the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_audit_logs', to='company_management.organization')),
            ],
            options={
                'verbose_name': 'Company Audit Log',
                'verbose_name_plural': 'Company Audit Logs',
                'db_table': 'company_management_audit_logs',
                'ordering': ['-created_at'],
                'permissions': [('view_company_audit_log', 'Can view company audit logs')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role name (e.g., Loan Officer, Reviewer)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the role responsibilities')),
                ('can_view_loan_application', models.BooleanField(db_index=True, default=False, help_text='Can view pending loan application details')),
                ('can_approve_loan_application', models.BooleanField(db_index=True, default=False, help_text='Can approve pending loan applications')),
                ('can_decline_loan_application', models.BooleanField(db_index=True, default=False, help_text='Can decline pending loan applications')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='HR admin who created this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='company_management.organization')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this user membership is active')),
                ('force_password_change', models.BooleanField(default=True, help_text='Whether user must change password on first login')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Timestamp of last password change', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful login', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='HR admin who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_users', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='company_management.organization')),
                ('user', models.ForeignKey(help_text='User account', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to this user', on_delete=django.db.models.deletion.PROTECT, related_name='organization_users', to='company_management.role')),
            ],
            options={
                'verbose_name': 'Organization User',
                'verbose_name_plural': 'Organization Users',
                'db_table': 'organization_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_8a4b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='company_man_event_t_184394_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='company_man_user_id_ac2a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='company_man_organiz_8f4226_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['result', 'created_at'], name='company_man_result_ea508e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='company_man_created_c5cf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'is_active'], name='roles_organiz_1c97c0_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'name'], name='roles_organiz_9daa34_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['can_view_loan_application'], name='roles_can_vie_90e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['can_approve_loan_application'], name='roles_can_app_1569b5_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['can_decline_loan_application'], name='roles_can_dec_c2840a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'user'], name='organizatio_organiz_a29000_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_49f94b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_b42f33_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_5200f6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['force_password_change'], name='organizatio_force_p_6ebeef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('organization', 'user')},
        ),
    ]
