# Generated by Django 5.0.8 on 2026-02-18 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.IntegerField(help_text='Month of remittance (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.IntegerField(help_text='Year of remittance')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount remitted in KES', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('proof_document', models.FileField(help_text='Proof of payment (bank slip, transfer receipt, etc.)', upload_to='remittance_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When this remittance was confirmed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes or comments about this remittance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Admin who confirmed this remittance', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_remittances', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='employers.employer')),
                ('submitted_by', models.ForeignKey(help_text='HR manager who submitted this remittance', limit_choices_to={'role': 'hr_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_remittances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remittance',
                'verbose_name_plural': 'Remittances',
                'db_table': 'remittances',
                'ordering': ['-period_year', '-period_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Expected deduction amount for this loan', max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount received (if matched)', max_digits=12)),
                ('is_matched', models.BooleanField(db_index=True, default=False, help_text='Whether expected and received amounts match')),
                ('notes', models.TextField(blank=True, help_text='Notes about this reconciliation record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_records', to='loans.loanapplication')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='reconciliation.remittance')),
            ],
            options={
                'verbose_name': 'Reconciliation Record',
                'verbose_name_plural': 'Reconciliation Records',
                'db_table': 'reconciliation_records',
                'ordering': ['loan_application__application_number'],
            },
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['employer', 'period_year', 'period_month'], name='remittances_employe_2e63a1_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['status'], name='remittances_status_f94ef0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remittance',
            unique_together={('employer', 'period_month', 'period_year')},
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['remittance', 'is_matched'], name='reconciliat_remitta_72565e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationrecord',
            unique_together={('remittance', 'loan_application')},
        ),
    ]
