# Generated by Django 5.0.8 on 2026-02-18 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, help_text='Unique application number (format: 254L + 8 digits)', max_length=20, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Loan principal amount in KES (5,000 - 5,000,000)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('5000.00')), django.core.validators.MaxValueValidator(Decimal('5000000.00'))])),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Interest rate (default 5% = 0.0500)', max_digits=5)),
                ('repayment_months', models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (9, '9 months'), (12, '12 months')], help_text='Number of months for repayment')),
                ('total_repayment', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount to be repaid (principal + interest)', max_digits=12, null=True)),
                ('monthly_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary deduction amount', max_digits=12, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the loan (optional)')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review_hr', 'Under HR Review'), ('under_review_admin', 'Under 254 Capital Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], db_index=True, default='submitted', max_length=30)),
                ('disbursement_date', models.DateField(blank=True, help_text='Date when loan was disbursed', null=True)),
                ('first_deduction_date', models.DateField(blank=True, help_text='Date of first salary deduction', null=True)),
                ('disbursement_method', models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa')], max_length=10, null=True)),
                ('disbursement_reference', models.CharField(blank=True, help_text='Transaction reference for disbursement', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review_hr', 'Under HR Review'), ('under_review_admin', 'Under 254 Capital Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], max_length=30)),
                ('comment', models.TextField(help_text='Comment or reason for status change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who made this status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_status_changes', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Status History',
                'verbose_name_plural': 'Loan Status Histories',
                'db_table': 'loan_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField(help_text='Installment number (1, 2, 3, etc.)')),
                ('due_date', models.DateField(help_text='Date when this installment is due (usually 25th of month)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be deducted for this installment', max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Remaining balance after this installment', max_digits=12)),
                ('is_first_deduction', models.BooleanField(default=False, help_text='Whether this is the first deduction')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this installment has been paid')),
                ('paid_date', models.DateField(blank=True, help_text='Date when this installment was actually paid', null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Repayment Schedule',
                'verbose_name_plural': 'Repayment Schedules',
                'db_table': 'repayment_schedules',
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['application_number'], name='loan_applic_applica_c66ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='loan_applic_status_2fc934_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['employee', 'status'], name='loan_applic_employe_8377e5_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['employer', 'status'], name='loan_applic_employe_1d5dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['disbursement_date'], name='loan_applic_disburs_43f006_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['created_at'], name='loan_applic_created_15dc53_idx'),
        ),
        migrations.AddIndex(
            model_name='loanstatushistory',
            index=models.Index(fields=['application', 'created_at'], name='loan_status_applica_2eecd9_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['loan', 'installment_number'], name='repayment_s_loan_id_b70538_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['due_date'], name='repayment_s_due_dat_710f73_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['is_paid'], name='repayment_s_is_paid_c3db44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan', 'installment_number')},
        ),
    ]
