# Generated by Django 5.0.8 on 2026-02-26 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether the employee has accepted the terms and conditions'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the employee accepted the terms and conditions', null=True),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['terms_accepted'], name='loan_applic_terms_a_839edb_idx'),
        ),
    ]
