# Generated by Django 5.0.8 on 2026-03-11 12:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_terms_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(help_text='Date when payment was received')),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Amount received in this payment', max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], help_text='Method of payment', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number (e.g., M-Pesa code)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment', null=True)),
                ('early_payment_discount_applied', models.BooleanField(default=False, help_text='Whether early payment discount was applied')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount if early payment', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(help_text='Loan application this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='loans.loanapplication')),
                ('recorded_by', models.ForeignKey(help_text='Admin who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Payment',
                'verbose_name_plural': 'Manual Payments',
                'db_table': 'manual_payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['loan', 'payment_date'], name='manual_paym_loan_id_a13c8a_idx'), models.Index(fields=['payment_date'], name='manual_paym_payment_ec47e1_idx'), models.Index(fields=['payment_method'], name='manual_paym_payment_f80dc7_idx')],
            },
        ),
    ]
