# Generated by Django 5.0.8 on 2026-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_add_bank_details_to_loan_application'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencylog',
            new_name='idempotency_idempot_b06070_idx',
            old_name='idempotency_idempot_a5f8c3_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencylog',
            new_name='idempotency_expires_434283_idx',
            old_name='idempotency_expires_2f7d91_idx',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review_admin', 'Under 254 Capital Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='loanstatushistory',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review_admin', 'Under 254 Capital Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], max_length=30),
        ),
    ]
