# Generated by Django 5.0.8 on 2026-09-08 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_rename_idempotency_idempot_a5f8c3_idx_idempotency_idempot_b06070_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_method',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')], default='flat', help_text='Interest calculation method used for this loan', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Monthly interest rate (default 5% = 0.0500)', max_digits=5),
        ),
    ]
