# Generated by Django 5.0.8 on 2026-09-26 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loanapplication_repayment_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='repayment_months',
            field=models.IntegerField(help_text='Number of months for repayment (no upper limit)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
