# Generated by Django 5.0.8 on 2026-03-11 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the client', max_length=255)),
                ('national_id', models.CharField(help_text='National ID number', max_length=20)),
                ('mobile', models.CharField(help_text='Mobile phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID at employer organization', max_length=100, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Original loan amount (principal)', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate as percentage (e.g., 5 for 5%)', max_digits=5)),
                ('start_date', models.DateField(help_text='Loan start date')),
                ('repayment_period', models.IntegerField(help_text='Repayment period in months')),
                ('disbursement_date', models.DateField(help_text='Date when loan was disbursed')),
                ('disbursement_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], help_text='Method of disbursement', max_length=10)),
                ('total_due', models.DecimalField(decimal_places=2, help_text='Total amount due (principal + interest)', max_digits=12)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, help_text='Monthly deduction amount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, help_text='Outstanding balance', max_digits=12)),
                ('loan_status', models.CharField(choices=[('Active', 'Active'), ('Fully Paid', 'Fully Paid'), ('Defaulted', 'Defaulted'), ('Restructured', 'Restructured')], default='Active', help_text='Current loan status', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for this record', max_length=20)),
                ('entered_by', models.CharField(blank=True, help_text='Name of admin who entered this record', max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(help_text='Employer organization', on_delete=django.db.models.deletion.CASCADE, related_name='existing_clients', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Existing Client',
                'verbose_name_plural': 'Existing Clients',
                'db_table': 'existing_clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_status'], name='existing_cl_approva_5668e2_idx'), models.Index(fields=['loan_status'], name='existing_cl_loan_st_7107e1_idx'), models.Index(fields=['employer'], name='existing_cl_employe_af5e8f_idx'), models.Index(fields=['national_id'], name='existing_cl_nationa_4cc28a_idx'), models.Index(fields=['mobile'], name='existing_cl_mobile_d070e4_idx')],
            },
        ),
    ]
